/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSiteContentRouteImport } from './routes/api/public/site-content'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiAdminLeadsRouteImport } from './routes/api/admin/leads'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteContentRoute = ApiPublicSiteContentRouteImport.update({
  id: '/api/public/site-content',
  path: '/api/public/site-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLeadsRoute = ApiAdminLeadsRouteImport.update({
  id: '/api/admin/leads',
  path: '/api/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/api/admin/leads': typeof ApiAdminLeadsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/pricing'
    | '/api/admin/leads'
    | '/api/public/contact'
    | '/api/public/site-content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/pricing'
    | '/api/admin/leads'
    | '/api/public/contact'
    | '/api/public/site-content'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/pricing'
    | '/api/admin/leads'
    | '/api/public/contact'
    | '/api/public/site-content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PricingRoute: typeof PricingRoute
  ApiAdminLeadsRoute: typeof ApiAdminLeadsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicSiteContentRoute: typeof ApiPublicSiteContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-content': {
      id: '/api/public/site-content'
      path: '/api/public/site-content'
      fullPath: '/api/public/site-content'
      preLoaderRoute: typeof ApiPublicSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/leads': {
      id: '/api/admin/leads'
      path: '/api/admin/leads'
      fullPath: '/api/admin/leads'
      preLoaderRoute: typeof ApiAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PricingRoute: PricingRoute,
  ApiAdminLeadsRoute: ApiAdminLeadsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicSiteContentRoute: ApiPublicSiteContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
